apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundedcontext1353
  labels:
    app: boundedcontext1353
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundedcontext1353
  template:
    metadata:
      labels:
        app: boundedcontext1353
    spec:
      containers:
        - name: boundedcontext1353
          image: "username/boundedcontext1353:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
