server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: appointment
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**, 
        - id: management
          uri: http://localhost:8083
          predicates:
            - Path=/medicalInformations/**, 
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/bills/**, 
        - id: boundedcontext1353
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: appointment
          uri: http://appointment:8080
          predicates:
            - Path=/appointments/**, 
        - id: management
          uri: http://management:8080
          predicates:
            - Path=/medicalInformations/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/bills/**, 
        - id: boundedcontext1353
          uri: http://boundedcontext1353:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
